### ISSUE TITLE
Can't launch builds from Xcode 15 beta

### ISSUE THREAD

**Issue by JacobSyndeo** [johnno1962/InjectionIII#454] opened 2023-08-01 00:27 UTC
When trying to run a build made using Xcode 15 beta, the app crashes on launch with the following message in the console:
```
dyld[63708]: Symbol not found: section$end$__DATA$__llvm_prf_vnds
  Referenced from: <[UUID]> /Users/[me]/Library/Developer/Xcode/DerivedData/[my app]-ffhgkgubebddiccmqlcnzrfhwidu/Build/Products/Debug/[my app]/Contents/MacOS/[my app]
  Expected in:     <[exact same UUID]> [exact same path as above]
```

Meanwhile, it (usually) works just fine when built using Xcode 14.

**Comment by johnno1962** [comment] 2023-08-01 07:20
Hi, I'm not seeing that at the moment but the error rings a bell. What beta version is this/which iOS/app version etc. Have you tried a build clean? Do you have test coverage enabled are few things you could try.

**Comment by JacobSyndeo** [comment] 2023-08-03 15:43
Thanks for the reply!

- This is Xcode 15 beta 5, but I've seen this with beta 4 and at least one earlier beta of Xcode 15. So it's likely every version of 15, at least for my setup.
	- When I use Xcode 14, I have never seen this error. The only issue I hit there is that it sometimes can't find my build logs, and I have to delete DerivedData, but that's a separate issue.
- It's a macOS app, and my system is running 13.4.1 (c).
- I have tried cleaning, as well as deleting DerivedData.
- Code coverage is enabled… should this be disabled? It doesn't appear to cause any issues for Xcode 14.
- Just tried the HotReloading package (removing, of course, the call to Injection from my AppDelegate), but the error message is identical.

**Comment by johnno1962** [comment] 2023-08-03 18:35
Can you try without code coverage? This sort of symbol is often related to that. When it doesn't find your build logs you should just be able to edit a file and rebuild to refresh them rather than having to clean/rebuild or delete DerivedData. Just seen your edit; It's always code coverage that trips things up. Who knows what the issue is with Xcode 15. We'll have to see if it resolves itself by the time they do a final release.

**Comment by johnno1962** [comment] 2023-09-13 17:39
Closing this as there is a workaround of not gathering code coverage. Is this still a problem with the Xcode 15 release candidate?

**Closed by johnno1962** 2023-09-13 17:39 UTC
