### ISSUE TITLE
counld not find file

### ISSUE THREAD

**Issue by starFelix** [johnno1962/InjectionIII#3] opened 2017-11-29 06:59 UTC
I try to use it in my project. But I found that it can no work as it's ok in demo.
The error I got is as below:
```
gunzip: error writing to output: Broken pipe
Compiling /pat/to/tofile.m

real	0m0.057s
user	0m0.039s
sys	0m0.012s
*** Re-compilation failed (/tmp/eval3.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/path/to/somheader.h' referenced by AST file '/Users/sfelixzhu/Library/Developer/Xcode/DerivedData/xxxxProject-csjzipupumxtbqccculhnzlqajfz/Build/Intermediates.noindex/PrecompiledHeaders/somPreCompileFile.pch.pch''
1 error generated.
```
I guessed the problem is my project is very large so the activitylog is large too. But I cannot resolve the error. I used to inject the project by injectionApp and it worked well.

By the way, I have tried to clean the project and rebuilt it . But it didn't work.

**Comment by johnno1962** [comment] 2017-11-29 07:46
Hi, have a look at running /tmp/eval<N>.sh to see what the problem is or could you email it to me injection at johnholdsworth dot com. It seems to have found the compile command OK. Would be good to work out the problem if it used to work in InjectionApp. Are you using the new build system?

**Comment by starFelix** [comment] 2017-11-29 08:57
I have check the `.sh` file. It looks like all is right. I'm sorry I can't email the file to you because of security.

And I don't know what the `new build system` mean？

**Comment by johnno1962** [comment] 2017-11-29 09:02
Can you try running the file after editing off the extra cruft at the string? This is what the app does. “new build system” is part of Xcode 9. If you’re not ware of it you’re probably not using it.

**Comment by starFelix** [comment] 2017-11-29 09:28
I have tried to running the file in terminal after deleting the part of `-o .....` . And It works fine, only warning and no error.

**Comment by starFelix** [comment] 2017-11-29 09:41
I have email you the sh file.

**Comment by johnno1962** [comment] 2017-11-29 13:08
I’ve prepared a test version of the app which produces a file /tmp/eval<N>.final.sh which is the command actually executed after minimal processing. There  must be a difference in escaping or something if you say the edited eval<N>.sh command works. Can you look at the differences please?

**Comment by starFelix** [comment] 2017-11-30 05:35
I'm sorry that I give you the wrong information. In fact, the `eval.sh` file works in the terminal without changing anything. And the ".command.sh" works in terminal too. I have compared two files and they are almost same except the `time` command.

I checked the code how to run shell in bundle. Maybe there is something different between `execve` and terminal?

I used to run shell with the below setting
```
    NSTask *task = [NSTask new];
    [task setLaunchPath:@"/bin/sh"];
    [task setArguments:@[self.scriptPath]];
    [task setCurrentDirectoryPath:[self lastFolderPath]];
    task.environment = @{@"LC_ALL":@"en_US.UTF-8",@"LANGUAGE":@"en_US.UTF-8",@"LANG":@"en_US.UTF-8",@"PATH":@"/usr/bin:/bin:/usr/sbin:/sbin"};
```
It seems that lacks the environment. I tried to add these to `execve` but I got errors.

**Comment by johnno1962** [comment] 2017-11-30 06:24
I’m beginning to get an idea what the problem might be here. Due to the new version of injection’s root being “SwiftEval” all build commands are run using execve in the simulator 😱. Everything seems to run except in the simulator filenames are case sensitive i.e. HeAdEr.h will not be the same as Header.h. Can you check this is not the case here? The headers where precompiled on OSX but the incremental compile will be trying to open the header inside the simulator’s OS. Eventually I’ll have to change this no doubt to run builds on OSX but this could be the problem at the moment.

**Comment by starFelix** [comment] 2017-11-30 06:50
Sorry,I had no idea what you mean. Did you mean some file named `Header.h`, but it's inclued as `HeAdEr.h`? If it is your meaning, I think this not the problem with caused the error. I have checked the project . The error said that it cannot find the file named "SomeHeader.h", and I cannot find anything like "someheader,someHeader,Someheader" in my project.

**Comment by johnno1962** [comment] 2017-11-30 06:55
It’s precompiling in a header you don’t reference in your project at all? It’s not in a pod or something?

**Comment by starFelix** [comment] 2017-11-30 07:01
Yes, I have referenced the file somewhere. What I means is the file name and import are case equal.

**Comment by johnno1962** [comment] 2017-11-30 07:19
Seems like I’ll have to move the compile onto OSX somehow which I was trying to avoid but it's where it should be.

**Comment by starFelix** [comment] 2017-11-30 07:31
Why you didn't want to move the compile onto OSX?

**Comment by starFelix** [comment] 2017-11-30 08:08
I have create a demo project which contain the `execve` code. It can build for iOS or macOS. In my test, the `eval.sh` works in macOS and doesn't work in iOS.

**Comment by johnno1962** [comment] 2017-11-30 08:43
Ok, I’ve uploaded a version that compiles on OSX if you want to give it a try. It gives slightly less feedback but I can work on that if it solves your problem.

**Comment by starFelix** [comment] 2017-11-30 10:48
Still no work...
The file named "eval.log" is empty. But I get the output in console:
```
ld: warning: ignoring file /tmp/eval2.o, file was built for i386 which is not the architecture being linked (x86_64): /tmp/eval2.o
```

**Comment by johnno1962** [comment] 2017-11-30 11:22
Are you building/running 32 bit? That’s not supported in the new version.

**Comment by johnno1962** [comment] 2017-11-30 12:25
Right, I’ve uploaded a version that supports 32 bit apps! Can you test it out?

**Comment by starFelix** [comment] 2017-11-30 13:02
It looks very strange after updating the project. The fileWatcher's callback would not be invoked, so even though I changed the files would not cause rebuilding.

**Comment by johnno1962** [comment] 2017-11-30 13:08
Are you watching the right project? The project is taken from the active project when the app starts.

**Comment by starFelix** [comment] 2017-11-30 13:18
I found the real reson is the injection was stuck on the code `bundlePath = [self readString]` in `InjectionServer.mm`.
I noticed that the function `runInBackground` had removed some code. Is it right?

**Comment by johnno1962** [comment] 2017-11-30 13:28
Perhaps you have very long paths. I’ve moved the connection setup to the background thread are you building yourself or using the binary (updated)

**Comment by starFelix** [comment] 2017-11-30 14:03
It can rebuild now. But still had the error said `symbol not found`. It looks like all symbol cannot found.

**Comment by starFelix** [comment] 2017-11-30 14:14
It can rebuild now. But still said symbol not found.
I found the symbol which cannot be found are in other framework or is created by runtime.

**Comment by johnno1962** [comment] 2017-11-30 14:20
Is the symbol in a framework that is in the app bundle? It should be linking with them. Are you using Google Analytics or any other binary frameworks?

**Comment by starFelix** [comment] 2017-11-30 14:30
Yes,the framework is in the app bundle. In fact, it's a subProject and it's target is a dynamic framework. I found the setting of `Symbols Hidden by Default` is YES. Is it the problem?

**Comment by johnno1962** [comment] 2017-11-30 14:31
Could easily be. Injecting something that refers to hidden symbols can be problematic. Other files should be OK. Did this work with the old injection?

**Comment by starFelix** [comment] 2017-11-30 14:36
I have checked .  It didn't work either with the old injection. So which settings can I change? I found that only change `Symbols Hidden by Default` would not work.

**Comment by starFelix** [comment] 2017-11-30 14:42
By the way, the error below still exist, the injected code was in a subProject.
```
ld: warning: ignoring file /tmp/eval2.o, file was built for i386 which is not the architecture being linked (x86_64): /tmp/eval2.o
```

It seems to build on a wrong architecture.

**Comment by johnno1962** [comment] 2017-11-30 15:18
Strange "Symbols Hidden by Default” didn’t affect the framework. You tried “no” right? I’ve pushed a new version that re-instates the filtering by target architecture when looking for the compile which should fix the last problem you mentioned. Bit by bit this is becoming the old Injection!

**Comment by johnno1962** [comment] 2017-12-01 07:40
Great, thanks for sticking with the various iterations. Closing this now.

**Closed by johnno1962** 2017-12-01 07:40 UTC

**Comment by starFelix** [comment] 2018-01-18 12:33
@johnno1962 I have a question that if there are a binary framework in my project, it means I cannot inject files related this framework? Have any way to resolve it?

**Comment by johnno1962** [comment] 2018-01-18 16:45
What is the error?

**Comment by starFelix** [comment] 2018-01-19 02:50
such like this: `dlopen() error: dlopen(/tmp/eval7.dylib, 2): Symbol not found: _OBJC_CLASS_$_CFT_F234309`

In my project,the architecture like `(MainProject (big dynamic Framework (somthing static library)))`
when I try to inject the files which related the static libray,and these files are in framework, I will get the error.
