### ISSUE TITLE
 Expected in: flat namespace

### ISSUE THREAD

**Issue by AsTryE** [johnno1962/InjectionIII#201] opened 2019-12-20 02:57 UTC
*** dlopen() error: dlopen(/Users/apple/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib, 2): Symbol not found: _$s9Ehospital12TGLayoutSizeC5equal_9increment8multipleA2CSg_12CoreGraphics7CGFloatVAJtFfA0_
  Referenced from: /Users/apple/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib
  Expected in: flat namespace
 in /Users/apple/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval103.dylib ***

**Comment by spnkr** [comment] 2020-03-11 00:34
i get this with nillable function parameters with default values. e.g. if i have a function like the one below anywhere in my project, i get this injection error most of the time when i change anything else.

```
public func setImage(withURL url: URL,
                         cacheKey: String? = nil,
                         completion: ((AFIDataResponse<UIImage>) -> Void)? = nil) {
```

**Comment by spnkr** [comment] 2020-04-29 22:07
@johnno1962 if i want to try to debug this myself, any tips on where to start?

**Comment by johnno1962** [comment] 2020-04-29 22:40
Hi, we were discussing this just yesterday; it would nice to fix this but I don’t believe there is much we can do about it. I think in happens when you inject a file that calls/refers to a method with default arguments. Swift seems to create a special symbol for the defaulted call which isn’t visible to code when it is dynamically loaded for some reason. If you supply the default values at the call site in the file you are injecting you should be ok. If you want to pursue it create a error in the file you are working with and inject it and have a look in the script the error message mentions to find out the object file and look at the symbols it refers to and compare them to that defined in the executable. But this will just tell you what the error message does already. If there is a fix it is likely to be a change to Swift compiler to do with symbol visibility.

**Comment by zenangst** [comment] 2020-04-30 04:59
@johnno1962 do you know if this is a known issue with the compiler? I mean, is it causing issue for other projects and will eventually be fixed or is it more "by-design"? Maybe a vague question but I'd just thought I'd ask :)

**Comment by johnno1962** [comment] 2020-04-30 07:12
I’m a bit hazy on the details but this would appear to be by design. I doubt fixing it would be a priority. It’s the same issue as when symbols are marked with hidden visibility such as Google analytics. The app builds ok but the hidden symbols are not visible when you dynamically load.

**Comment by johnno1962** [comment] 2020-05-01 06:00
HI @spnkr any chance you could put together a simple project that replicates this problem and I can take a look at it. The idea I have is to use something along the lines of unhide if that is indeed the problem but at the moment I can’t replicate it this end with Xcode 11.4.1

**Comment by Katsz** [comment] 2020-06-23 13:58
I've faced same issue but wasn't able to replicate it as a sample project myself either. But what is especially strange - renaming method in source project back and forth somehow fixed this issue. And I can't break it again ever since `¯\_(ツ)_/¯`

**Comment by johnno1962** [comment] 2020-06-23 15:30
Very, very, very weird!

**Comment by mohok** [comment] 2020-07-26 23:35
Same error!

```
💉 Loading .dylib ...
💉 *** dlopen() error: dlopen(/var/folders/kl/qqfpymjx64z7k3wgq3pqc4z80000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib, 2): Symbol not found: _$s0030__for_iPad_EqIaHbBhqJbbaArqJaqd11GlobalValueVMn
  Referenced from: /var/folders/kl/qqfpymjx64z7k3wgq3pqc4z80000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib
  Expected in: flat namespace
 in /var/folders/kl/qqfpymjx64z7k3wgq3pqc4z80000gp/T/com.johnholdsworth.InjectionIII/eval101.dylib ***
```
macOS 10.15.4, Xcode 11.6, iPad 7th 13.0 simulator

**Comment by johnno1962** [comment] 2020-07-27 06:20
Hi, for some reason if you call functions that have default parameters you can get undefined symbols on injection. Could this be the case here?

**Comment by skrew** [comment] 2020-08-11 23:35
It's the case for me too, so i can confirm 👍🏻

**Comment by johnno1962** [comment] 2020-08-12 04:55
Hi @skrew, this is a known problem but one I’ve been unable to replicate with a small project to look at. If you ever come up with an example project that replicates it or are prepared to screen share please let me know.

**Comment by skrew** [comment] 2020-08-12 13:03
Hi @johnno1962 A little test project

When you will try to inject, you will see:

```
*** dlopen() error: dlopen(/var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib, 2): Symbol not found: _$s13TestInjection15QTNavigationRowC4text10detailText4icon6object13customization6action21accessoryButtonActionACyxGSS_AA08QTDetailG0OAA6QTIconOSgypSgySo15UITableViewCellC_AA5QTRow_AA0T5StyleptcSgyAaT_pcSgAWtcfcfA1_
  Referenced from: /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib
  Expected in: flat namespace
 in /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib ***
```


[TestInjection.zip](https://github.com/johnno1962/InjectionIII/files/5062801/TestInjection.zip)

**Comment by johnno1962** [comment] 2020-08-12 15:33
Thanks very much for the test project! It was what I thought it was and it is fixable but it may take a bit of time.. bear with me.

**Comment by johnno1962** [comment] 2020-08-12 15:33
Thanks very much for the test project! It was what I thought it was and it is fixable but it may take a bit of time.. bear with me.

**Comment by johnno1962** [comment] 2020-08-12 15:33
Thanks very much for the test project! It was what I thought it was and it is fixable but it may take a bit of time.. bear with me.

**Comment by johnno1962** [comment] 2020-08-12 15:33
Thanks very much for the test project! It was what I thought it was and it is fixable but it may take a bit of time.. bear with me.

**Comment by johnno1962** [comment] 2020-08-12 22:49
OK, I have a solution. It's not 100% but it works provided you have built your project more than once before trying to inject a file referring to a function with default arguments. Youl need to clone and build the [unhide project](https://github.com/johnno1962/unhide) then add the following as a "Run Script" at the end of the project's "Build Phases":
```shell
UNHIDE=~/bin/unhide.sh
if [ -f $UNHIDE ]; then
    $UNHIDE
else
    echo "File $UNHIDE used for code Injection does not exist."
fi
```
It's hot of the press, but if it resolves your problem I'll try to tidy it up but it would be very difficult to resolve the "you need to build the project more than once" before injecting a default argument limitation.

**Comment by skrew** [comment] 2020-08-12 23:29
Ok i will try. Do i need to remove this script for the appstore release ?

(And thanks to you for this project ! I use it for years and we had already do a screen share 5 years ago if i remember :) )

**Comment by skrew** [comment] 2020-08-13 01:35
Ok i tested on my actual project:
- The build fail with `Can't find ordinal for imported symbol for architecture x86_64` (it use mixed Swift / Obj-C / C code) so i removed the `interposable` flag
- The unhide script seem to be executed, and i got a lot of `unhide: Missing symtab or dylib cmd xxx.o: 0x7f9d63cd1888 & 0x0` (Not verified but it's look like it's all the external SPM packages)

The injection seems to works now, but:
- If i use `@objc injected()` the app crash
- If i use the notification `INJECTION_BUNDLE_NOTIFICATION` it seem to works (i can see the call in the logs) but reloading the view don't have any effect. In the logs i can see my reload call called... Also, if i put a breakpoint on my reload function, Xcode doesn't break

I think my project is too "big" and uses too many things that can make the injection fail (mixed languages, pods, SPM...) but if you want to look with a screen share, it's ok for me

**Comment by johnno1962** [comment] 2020-08-13 06:35
Wow, that’s quite a list of things the “fix” breaks. I’ve tweaked `unhide` to only publish these special default argument functions for now which should break less things if you want to give it a try. The real solution is to get a fix into the compiler. Don’t worry about the Missing syntax message. It’s interesting that you then get the “Can’t find ordinal” message as a result of the fix. Does it print any other information? That could be a help to find understanding what that problem is.

**Comment by skrew** [comment] 2020-08-13 22:56
I have just tested with the new `unhide` but the problem is back:
```
Loading .dylib ...
💉 *** dlopen() error: dlopen(/var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib, 2): Symbol not found: _$s11lxxx11QTSwitchRowC4text10detailText11switchValue4icon6object13customization6actionACyxGSS_AA08QTDetailF0OSgSbAA6QTIconOSgypSgySo15UITableViewCellC_AA5QTRow_AA0R5StyleptcSgyAaU_pcSgtcfcfA0_
  Referenced from: /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib
  Expected in: flat namespace
 in /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib ***
```

BTW i have see your patch, it's only "that" ? What do you think about providing a pre-compiled (and patched) compiler, attached to a precise Xcode build / version ?

**Comment by johnno1962** [comment] 2020-08-13 23:15
Hmm, strange. Can you roll back your unhide to the previous commit and check it works again please. It wasn't a very big change. We'll see what they have to say about the patch but I doubt it would be worthwhile to make patched toolchains available just to use injection. If we can get unhide working that's the best we can do for now. It's a bit of an edge case,

**Comment by skrew** [comment] 2020-08-13 23:18
Ok i will test with the previous version.
I think the chances of the patch being accepted are very low, it should be active only in Debug or with a special flag...
But even with that...

**Comment by skrew** [comment] 2020-08-13 23:30
Ok my fault, i had enabled "Enable vaccine" to test yesterday...
The new `unhide` works, but my view is not refreshed, which i don't understand... I can see functions called in the logs, but...

**Comment by johnno1962** [comment] 2020-08-14 00:15
Did you add back the interposable flag?

**Comment by skrew** [comment] 2020-08-14 00:24
On this project, i can't... The build fail with `ld: can't find ordinal for imported symbol for architecture x86_64`

**Comment by johnno1962** [comment] 2020-08-14 00:31
So it wasn’t to do with `unhide`, using injection without the interposable flag is not reliable. Are the new versions of your functions taking effect if you change a log message?

**Comment by skrew** [comment] 2020-08-14 00:36
No, i have added a `print("test1")`, and changed with `print("test2")` but after injection i still see `test1`

**Comment by johnno1962** [comment] 2020-08-14 01:00
So it's not injecting. Without the interposable flag it will not work. I'll need to fix the ordinal problem before you'll be able to use the new injection on your particular project. Did the previous version (which you can download from releases work?

**Comment by skrew** [comment] 2020-08-14 01:03
it worked before, yes, but i have not worked on this project with injection for several months. If you want to test something with screen share, i will be there for 1 hour before sleeping :)

**Comment by johnno1962** [comment] 2020-08-14 01:11
Can you send through your TeamViewer details to github@johnholdsworth.com please and I can take quick look. It may be possible to produce a hybrid version of injection which work the old way and the new way later.

**Comment by skrew** [comment] 2020-08-14 11:35
Ok back :)
So i continued the tests.

While it works on the test controller, it fail on another controller:
```
Loading .dylib ...
💉 *** dlopen() error: dlopen(/var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/net.xxx.InjectionIII/eval104.dylib, 2): Symbol not found: _$sSo10LMRootViewC11xxxE10topPadding06bottomE015backgroundColor_4withAB12CoreGraphics7CGFloatV_AJSo7UIColorCSgSo6UIViewCyABcSgtcfcfA_
  Referenced from: /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/net.xxx.InjectionIII/eval104.dylib
  Expected in: flat namespace
 in /var/folders/tz/ztl86kmd7hn5rww5ls57yvjw0000gn/T/net.xxx.InjectionIII/eval104.dylib ***
```

Also, when `unhide.sh` is active, the breakpoints in Xcode doesn't works anymore

**Comment by johnno1962** [comment] 2020-08-14 12:03
‘morning, I'll be honest I’m surprised breakpoints are working as well as they are though injecting [breaks self](https://github.com/johnno1962/InjectionIII/issues/248).

I'm not sure how far to chase default arguments. The new problem you mention seems to be a new variation and the symbol mentioned doesn't even demangle.  I've pushed a fix to `unhide` you could try for this case. Can you tell me the signature of the function being called (xxx?)?

**Comment by skrew** [comment] 2020-08-14 12:12
Ok i will test.
For the breakpoints, they doesn't works anymore, even without injection... just disabling `unhide.sh` script back breakpoints to life

**Comment by skrew** [comment] 2020-08-14 12:57
Ok i have patched your code detection in `unhide`, your check is not good for the last case (btw, my patch are not good too, just hardcoded the test :p)

But now it works and the breakpoints are back !

**Comment by johnno1962** [comment] 2020-08-14 13:00
How do you mean, you had to patch th unhide project? If so how?

**Comment by johnno1962** [comment] 2020-08-14 13:04
The code doesn't account for more than 10 default arguments. Is this the issue?

**Comment by skrew** [comment] 2020-08-14 13:09
Ok i got it ... The signature is `_$s11lillyplayer9TVOSToastC5frame5styleACSo6CGRectV_AA0B5StyleVSgtcfcfA0_`, it worked before but i think your new patch is not good for this case ?

**Comment by johnno1962** [comment] 2020-08-14 13:13
Are you sure this is the second build?

**Comment by johnno1962** [comment] 2020-08-14 13:14
Are you sure this is the second build?

**Comment by johnno1962** [comment] 2020-08-14 13:15
Are you sure this is the second build?

**Comment by johnno1962** [comment] 2020-08-14 13:16
OK, scratch the change then. Are you sure this is the second build?

**Comment by skrew** [comment] 2020-08-14 13:16
Now i have a signature which end with `A10_` so i was right ...
`_$sSo9LMRowViewC11xxxE6margin9topMargin07leadingF006bottomF008trailingF019horizontalAlignment08verticalK07spacing17isAlignToBaseline8baseline15backgroundColor6weight13ignoreMargins6anchor_4withAB12CoreGraphics7CGFloatVSg_A4VSo012LMHorizontalK0VSo010LMVerticalK0VAUSbSo10LMBaselineVSo7UIColorCSgAUSbSo8LMAnchorVSo6UIViewCdyABcSgtcfcfA10_`

**Comment by johnno1962** [comment] 2020-08-14 13:18
OK, I've pushed a change to unhide. I think the new limit of up to 100 should be enough.

**Comment by skrew** [comment] 2020-08-14 13:23
Ok it works... Injection & breakpoints ! I'm continue to works on my project and i will tell you if i found something else (i hope no ! :p)

**Comment by johnno1962** [comment] 2020-08-17 08:06
GM @skrew, I’ve pushed a minor change to `unhide` to only update object files where there is a default argument and made available a new [release candidate of InjectionIII](https://github.com/johnno1962/InjectionIII/releases/tag/2.2.1RC2) if you want to help with final testing of that. It should work the same as the version you have.

**Comment by skrew** [comment] 2020-08-17 23:06
Hi @johnno1962 i'm testing it right now, thanks

**Comment by zenangst** [comment] 2020-08-20 09:12
@skrew how's the new version working for you? 😀

**Comment by skrew** [comment] 2020-08-20 20:57
@zenangst Apart from a few small problems, it works pretty well ! I keep using it to try to find something else :)
Eg this code:
```
QTTapActionRow(text: "Next".localized(), action: { _ in
    <code disclosure>
})
```
Sometimes after an injection, the code in disclosure don't run anymore... But it's not happening everytime

**Comment by skrew** [comment] 2020-08-20 21:43
@zenangst Not yet, i'm about 20 days late on my project so I'm not hanging around too much anymore ! :)

**Comment by zenangst** [comment] 2020-08-20 21:44
@skrew I see, best of luck with the project, hope you nail it!

**Comment by ZexiFangkong** [comment] 2020-12-22 09:02
> ‘morning, I'll be honest I’m grateful breakpoints are working as well as they are though injecting can [break self](https://github.com/johnno1962/InjectionIII/issues/248).
> 
> I'm not sure how far to chase default arguments. The new problem you mention seems to be a new variation and the symbol mentioned doesn't even demangle. I've pushed a fix to `unhide` you could try for this case. Can you tell me the signature of the function being called (xxx?)?

This script works for me. The interesting thing is that after executing the script, the same error was reported after restarting the project for the first time. I thought the script did not solve the problem. To my surprise, I waited for about 10 minutes and restarted the project again. Found that solved my problem once, thank you very much

**Comment by johnno1962** [comment] 2020-12-22 09:13
Yes, its a feature of the script that you need to have built twice before it takes effect as there is no way to run the script between compiling and linking which would be more ideal.

**Comment by johnno1962** [comment] 2021-07-26 06:49
Closing this now as the "unhide" script has been. integrated into the InjectionIII app.

**Closed by johnno1962** 2021-07-26 06:49 UTC

**Comment by songxing10000** [comment] 2021-12-29 03:11
💉 Compiling /Users/dfpo/myProj/hilife-college-ios/hilifeElite/submodule/FanDengReading/GlobalOnlineSchoolSRC/Classes/View/SignUpNowSheetView.m
💉 Loading .dylib ...
💉 ⚠️ dlopen() error: dlopen(/Users/dfpo/Library/Developer/CoreSimulator/Devices/978AEE74-75D4-47B7-960B-AB882BE99539/data/Containers/Data/Application/2891BF5E-42A4-44E4-B494-58972BE52F3E/tmp/eval101.dylib, 0x0002): symbol not found in flat namespace '_OBJC_CLASS_$_HQTagView'

**Comment by songxing10000** [comment] 2021-12-31 03:10
Sorry, I don’t know, it may be caused by the project oc and swift mixed or upgrading macos system etc.
